In [10]:
import numpy as np
a=np.random.rand(10,1)
b=np.mean(a)
print("Mean",b)

Mean 0.4275899172885283


In [9]:
import numpy as np
a=np.random.rand(20,1)
b=np.std(a)
print("standard deviation",b)
c=(b)**2
print("variance",c)

standard deviation 0.2958592814283558
variance 0.08753271440730305


In [21]:
import numpy as np
a=np.random.rand(10,20)
b=np.random.rand(20,25)
c=np.matmul(a,b)
x=np.sum(c)
print(c)
print(x)

[[6.32666621 5.60717878 5.66682439 5.42012585 5.36361666 4.83682317
  5.53396468 5.14385146 2.95345325 5.16593216 6.0618844  5.10981143
  6.81815255 6.03253603 6.38543064 5.19379879 5.67321201 5.10654495
  4.45743053 5.86046729 6.18709709 6.25814732 5.06662842 6.26484691
  4.00420502]
 [5.93996513 5.38176169 4.35089474 4.10356045 4.23168473 4.47430161
  4.78206753 4.91502291 3.11918772 5.07702301 4.54077183 4.32105508
  5.64782121 5.31020154 5.20436405 4.51058978 5.47929426 5.17308909
  4.75023405 4.64381725 4.98360676 6.13653275 5.10192641 6.02522561
  3.25424791]
 [5.42697686 5.27891621 4.42201439 4.23966262 4.3433906  3.86195713
  4.90480549 5.0777872  3.40489449 4.30623504 4.87351606 4.0253596
  6.05755858 4.39683521 4.83786909 4.81965818 5.76161606 5.02436799
  4.06173766 5.45461273 5.19681714 6.05038009 4.17630471 5.46662372
  3.59622532]
 [5.9900922  5.17876112 4.48483397 4.47544816 4.56824826 3.8966191
  5.16811071 5.10727265 2.87191662 4.61681432 4.72907752 4.73200685
  5.5375

In [26]:
import numpy as np
a=np.random.rand(10,1)
y=lambda x:1/1+np.exp(-a)
z=np.array([y(ai) for ai in a])
print(z)

[[[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595]
  [2.29053385]
  [3.60784885]
  [2.67316958]
  [2.52232238]]

 [[2.18895502]
  [2.26819158]
  [2.29665484]
  [2.89228661]
  [3.36454636]
  [2.55855595